// Serves the RSS + sitemap feeds that the `turtle` service writes to the R2
// bucket bound as FEEDS (see wrangler.toml). The static site is generated by
// scripts/build.js and is immutable per Pages deploy, so these dynamic feeds
// can't live in stage/ — they're fetched from R2 on request instead.
//
// _headers rules do NOT apply to Function responses, so we set Cache-Control
// here (600s, matching turtle's S3 CacheControl). Every other request falls
// through via next() to the static asset pipeline, where _headers still applies.

export async function onRequest( context ) {
    const { request, env, next } = context;
    const path = new URL( request.url ).pathname;

    let key = null;
    let fallbackType = 'application/xml';

    if ( /^\/sitemap(\.[^/]+)?\.xml$/.test( path ) ) {
        // /sitemap.xml or /sitemap.<game>.xml
        key = path.slice( 1 );
    } else if ( /^\/[^/]+\/rss$/.test( path ) ) {
        // /<game>/rss
        key = path.slice( 1 );
        fallbackType = 'application/rss+xml';
    }

    if ( !key ) {
        return next();
    }

    const object = await env.FEEDS.get( key );

    if ( !object ) {
        return new Response( 'Not found', { status: 404 } );
    }

    return new Response( object.body, {
        headers: {
            'Content-Type': object.httpMetadata?.contentType || fallbackType,
            'Cache-Control': 'public, max-age=600',
        },
    } );
}
